

services:
  postgres:
    image: postgres:15
    container_name: postgres_container 
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tarot_db 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  redis:
    image: redis:7 
    container_name: redis_container 
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"] 

volumes:
  postgres_data:
  
